### ISSUE TITLE
PR: Upgrading webpack-cli + webpack breaks existing scripts

### ISSUE THREAD

**Issue by frank-dspeed** [microsoft/vscode-generator-code#279]
# Upgrading webpack-cli + webpack breaks existing scripts
More Details can be found here https://github.com/webpack/webpack-dev-server/issues/2424

i need to test the right parameters will create PR as soon as all edgecases are solved

```
pm run dev:client

> esbook@0.0.1 dev:client
> webpack-dev-server

node:internal/modules/cjs/loader:944
  throw err;
  ^

Error: Cannot find module 'webpack-cli/bin/config-yargs'
Require stack:
- /home/frank/notebooks/esbook/node_modules/webpack-dev-server/bin/webpack-dev-server.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)
    at Function.Module._load (node:internal/modules/cjs/loader:774:27)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/home/frank/notebooks/esbook/node_modules/webpack-dev-server/bin/webpack-dev-server.js:65:1)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/frank/notebooks/esbook/node_modules/webpack-dev-server/bin/webpack-dev-server.js'
  ]
}
```
showing what does happen when we switch to webpack serve without env parameters
```
frank@frank-MS-7821:~/notebooks/esbook$ npm run dev:client

> esbook@0.0.1 dev:client
> webpack serve

ℹ ｢wds｣: Project is running at http://localhost:8111/
ℹ ｢wds｣: webpack output is served from 
ℹ ｢wds｣: Content not from webpack is served from /home/frank/notebooks/esbook
⚠ ｢wdm｣: asset index.js 982 KiB [emitted] [minimized] [big] (name: main) 1 related asset
runtime modules 25.9 KiB 13 modules
orphan modules 18.1 KiB [orphan] 6 modules
modules by path ./node_modules/ 348 KiB
  modules by path ./node_modules/webpack-dev-server/ 21.2 KiB 12 modules
  modules by path ./node_modules/webpack/hot/ 4.46 KiB 5 modules
  modules by path ./node_modules/html-entities/lib/*.js 61 KiB 5 modules
  modules by path ./node_modules/url/ 37.4 KiB 3 modules
  modules by path ./node_modules/querystring/*.js 4.51 KiB 3 modules
modules by path ./src/client/ 5.88 KiB
  modules by path ./src/client/*.ts 3.32 KiB
    ./src/client/index.ts 2.21 KiB [built] [code generated]
    ./src/client/render.ts 1.11 KiB [built] [code generated]
  modules by path ./src/client/*.css 2.56 KiB
    ./src/client/style.css 1.87 KiB [built] [code generated]
    ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].use[1]!./src/client/style.css 710 bytes [built] [code generated]

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value.
Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  index.js (982 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (982 KiB)
      index.js


WARNING in webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

webpack 5.37.0 compiled with 4 warnings in 3239 ms
ℹ ｢wdm｣: Compiled with warnings.

```

## Todo
- [x] Migrate to webpack serve
- [x] create a new webpack.config.dev.json? needs evaluation maybe it is better to use oli parameters
  - [x] --mode development --env development --hot

**Comment by frank-dspeed** [comment]
After committing the changes the result is:

```
frank@frank-MS-7821:~/notebooks/esbook$ npm run dev:client

> esbook@0.0.1 dev:client
> webpack serve --mode development --env development --hot-only

ℹ ｢wds｣: Project is running at http://localhost:8111/
ℹ ｢wds｣: webpack output is served from 
ℹ ｢wds｣: Content not from webpack is served from /home/frank/notebooks/esbook
ℹ ｢wdm｣: asset index.js 1.06 MiB [emitted] (name: main)
runtime modules 25.9 KiB 13 modules
orphan modules 139 bytes [orphan] 2 modules
modules by path ./node_modules/ 367 KiB 31 modules
modules by path ./src/client/ 5.91 KiB
  modules by path ./src/client/*.ts 3.35 KiB
    ./src/client/index.ts 2.21 KiB [built] [code generated]
    ./src/client/render.ts 1.14 KiB [built] [code generated]
  modules by path ./src/client/*.css 2.56 KiB
    ./src/client/style.css 1.87 KiB [built] [code generated]
    ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].use[1]!./src/client/style.css 710 bytes [built] [code generated]
webpack 5.37.0 compiled successfully in 750 ms
ℹ ｢wdm｣: Compiled successfully.
No issues found.
```

**Comment by frank-dspeed** [comment]
@aeschli i have choosen to ping you directly to bump the issue up in your list pls forgive me.

**Comment by aeschli** [comment]
@connor4312 This is with the notebook generator

**Comment by connor4312** [comment]
The notebook generator no longer uses the webpack dev server, so this should no longer be an issue.
